/* Drop real logo files in src/assets/images/partners/ and point `logo` at them,
   e.g. logo: "/src/assets/images/partners/lupin.png".
   Until then the 3D cube renders a clean text wordmark fallback.
   `url` is each partner's own official site — the cube opens it on click. */
export const partners = [
  { name: "HMD Healthcare", url: "https://hmdhealthcare.com/" },
  { name: "Lupin", url: "https://www.lupin.com/" },
  { name: "Healthium", url: "https://healthiummedtech.com/" },
  { name: "Macleods", url: "https://www.macleodspharma.com/" },
  { name: "Concord Biotech", url: "https://concordbiotech.com/" },
  { name: "Sterimed", url: "https://www.sterimedgroup.com/" },
  { name: "Abbott Nutrition", url: "https://www.abbottnutrition.com/our-brands" },
  { name: "Meril", url: "https://www.merillife.com/" },
  { name: "Tuoren", url: "https://www.tuoren.in" },
  { name: "Nihon Kohden", url: "https://in.nihonkohden.com/en" },
  { name: "Smith+Nephew", url: "https://www.smith-nephew.com/en" },
  { name: "White Plus", url: "https://whiteplus.in" },
  { name: "Skanray", url: "https://skanray.com" },
  { name: "Midmark", url: "https://www.midmark.com" },
  { name: "Abbott", url: "https://www.abbott.co.in/" },
  { name: "Centroiid Meditech", url: "https://www.centroiidmeditech.com/" },
  { name: "Allied Medical", url: "https://www.alliedmed.in/" },
  { name: "Medicotronics", url: "https://medicotronics.com/" },
  { name: "Unijules", url: "https://www.unijules.com/" },
  { name: "RPG Life Sciences", url: "https://www.rpglifesciences.com/" },
  { name: "Aurolab", url: "https://www.aurolab.com/" },
  { name: "Apex", url: "https://apexlab.com/" },
  { name: "CMG Biotech", url: "https://cmgbiotech.com/pharma.php" },
  { name: "Reckon Diagnostics", url: "https://www.reckondiagnostics.com/" },
];
