/* Drop real logo files in src/assets/images/partners/ and point `logo` at them,
   e.g. logo: "/src/assets/images/partners/lupin.png".
   Until then the 3D cube renders a clean text wordmark fallback. */
export const partners = [
  { name: "HMD Healthcare" },
  { name: "Lupin" },
  { name: "Healthium" },
  { name: "Macleods" },
  { name: "Concord Biotech" },
  { name: "Sterimed" },
  { name: "Abbott Nutrition" },
  { name: "Meril" },
  { name: "Tuoren" },
  { name: "Nihon Kohden" },
  { name: "Smith+Nephew" },
  { name: "White Plus" },
  { name: "Skanray" },
  { name: "Midmark" },
  { name: "Abbott" },
  { name: "Centroiid Meditech" },
  { name: "Allied Medical" },
  { name: "Medicotronics" },
  { name: "Unijules" },
  { name: "RPG Life Sciences" },
  { name: "Aurolab" },
  { name: "Apex" },
  { name: "CMG Biotech" },
  { name: "Reckon Diagnostics" },
];
